name: Deploy to AWS Lightsail

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'

      - name: Copy files to Lightsail instance
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/ubuntu/app"

      - name: SSH and write .env file, install deps, restart app
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export PATH=$PATH:/usr/bin:/usr/local/node-20.9.0/bin
            cd /home/ubuntu/app
            cat <<EOF > .env
            PORT=${{ vars.PORT }}
            EMAIL_USER=${{ vars.EMAIL_USER }}
            APP_PASS=${{ vars.APP_PASS }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            DIRECT_URL=${{ secrets.DIRECT_URL }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            EOF
            npm install --production
            pm2 restart app || pm2 start index.js --name app
